branch-defaults:
  production:
    environment: production
  # (optional) Other branch-specific settings
  # (e.g. if you want a staging environment)
  master:
    environment: master
global:
  application_name: vision-app-backend
  default_ec2_keyname: null
  default_platform:
    arn:aws:elasticbeanstalk:us-west-1::platform/Docker running on
    64bit Amazon Linux/2.12.17
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
